### ISSUE TITLE
Delete attribute 

### ISSUE THREAD

**Issue by arnoldmq** [HDF-NI/hdf5.node#107]
Is there a way to delete an attribute? Like a groups attribute, I didn’t see anything in the documentation. The docs talk about deleting a group but not an attribute.

**Comment by rimmartin** [comment]
Hmmm, let me think about it. Try to find an easy way

**Comment by rimmartin** [comment]
I added a deleteAttribute function on files and groups.  It takes the name of attribute as argument.
https://github.com/HDF-NI/hdf5.node/blob/master/test/test_attributes.js#L89
If you try to readAttribute an attribute and it doesn't exist readAttribute will now throw an exception

**Comment by rimmartin** [comment]
this is in the master branch

**Comment by rimmartin** [comment]
will still look to tie it into
```
delete group.spaceGroup;
```
if it is possible

**Comment by rimmartin** [comment]
javascript _delete_ is now working on attributes
```
delete group.unitCell;
```
It does it directly; no additional step

**Comment by wank92** [comment]
I notice when I do an npm install, I do not get the delete attribute feature.
