### ISSUE TITLE
idea: prebuilt binaries

### ISSUE THREAD

**Issue by maxogden** [HDF-NI/hdf5.node#11]
Hey, so glad you're working on this module, it's long overdue in the npm ecosystem!

I wanted to suggest setting up cross platform prebuilt binaries. Here's a sort of blog post I did on the topic recently https://gist.github.com/maxogden/e81e0f1d222106146828

It should be pretty easy to hook up https://www.npmjs.com/package/node-pre-gyp here so that it can fall back to compilation in case the prebuilt binary for some platform/arch isn't available

**Comment by rimmartin** [comment]
Thank you @maxogden ,

I didn't know such was possible!  I'll read up on this.  Thanks for the links
