### ISSUE TITLE
Unable to read variable-length string attributes

### ISSUE THREAD

**Issue by scottwittenburg** [HDF-NI/hdf5.node#14]
Is there a plan to add support for variable-length string attributes?  It seems at the moment only fixed-length strings (as attributes) are supported.

Here is a link to a small example file which demonstrates the problem:

http://wikisend.com/download/692318/simple-nba.h5

**Comment by rimmartin** [comment]
Yes it needs added.  Thanks for the example.

Which nodejs version are you running with?

**Comment by scottwittenburg** [comment]
Thanks for looking into this :-)  I'm running with node version 4.2.2

**Comment by rimmartin** [comment]
Ok, I'll put it with the master branch; test and then republish

**Comment by rimmartin** [comment]
btw, the use of nodejs Buffer is now the same as using Uint8Array which has a major size limitation to 2 Gb;  am looking into streaming to overcome this change of the V8 that caused the node team to make Buffer derive completely from Uint8Array

**Comment by rimmartin** [comment]
Hi, I have  some code working for my own attribute example;  haven't been able to read http://wikisend.com/download/692318/simple-nba.h5 with HDFView or by api.

Are the attributes you are using on groups and/or datasets?

**Comment by scottwittenburg** [comment]
They are on a group.  I am able to read them with `h5dump` on linux, and I have a patch to `attributes.hpp` that reads them, if you are interested.  Or let me know if there is some other way I can help.  Thanks for your great work!

**Comment by rimmartin** [comment]
I meant to say couldn't open http://wikisend.com/download/692318/simple-nba.h5 with any tool; not just see variable length strings

**Comment by scottwittenburg** [comment]
Hmmm, I just downloaded it from there, and ran `h5dump` on it, and this is what I see:

```
HDF5 "/.../Downloads/simple-nba.h5" {
GROUP "/" {
   GROUP "info" {
      ATTRIBUTE "packageHash" {
         DATATYPE  H5T_STRING {
            STRSIZE H5T_VARIABLE;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
         DATA {
         (0): "457ba473cc529e0e6c2dac3c64f1865c"
         }
      }
      ATTRIBUTE "packageID" {
         DATATYPE  H5T_STRING {
            STRSIZE H5T_VARIABLE;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
         DATA {
         (0): "DEADBEEF87726342"
         }
      }
      ATTRIBUTE "packageName" {
         DATATYPE  H5T_STRING {
            STRSIZE H5T_VARIABLE;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
         DATA {
         (0): "NBA Player DAta (2014/2015)"
         }
      }
      ATTRIBUTE "parentPackage" {
         DATATYPE  H5T_STRING {
            STRSIZE H5T_VARIABLE;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
         DATA {
         (0): "NA"
         }
      }
      ATTRIBUTE "rootPackage" {
         DATATYPE  H5T_STRING {
            STRSIZE H5T_VARIABLE;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
         DATA {
         (0): "NA"
         }
      }
   }
}
}
```

**Comment by rimmartin** [comment]
If I left click t takes me to a page that downloads a movie of a gymnatics practice; called MAGpr1.MOV
If I right click and download and check it with h5debug I get
```bash
HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 0:
  #000: /home/roger/Software/hdf5-1.8.16/src/H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: /home/roger/Software/hdf5-1.8.16/src/H5Fint.c line 1087 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: /home/roger/Software/hdf5-1.8.16/src/H5Fsuper.c line 277 in H5F_super_read(): file signature not found
    major: File accessibilty
    minor: Not an HDF5 file
cannot open file
```

**Comment by rimmartin** [comment]
yea right-click is the html page

but left click goes to mov cip

**Comment by scottwittenburg** [comment]
Ok, now that's what I'm seeing too, though an hour or two ago, the data at that link was still my example, or perhaps my browser had cached the page.  I think that means I should no longer use wikisend.  Do you have any other suggestion for how I should share the file?

**Comment by rimmartin** [comment]
Seems a useful way; my mistake was right-clicking to download last week and not testing right away.  Could try it again.

```
npm owner ls
```
in a working folder of hdf5.node will give you my email too

**Comment by scottwittenburg** [comment]
Ok, I uploaded again, it says you should have 7 days to access the file:

http://wikisend.com/download/654088/simple-nba.h5

**Comment by rimmartin** [comment]
Thank you, can read and test with this

**Comment by rimmartin** [comment]
Test is working.  Been puzzling over when writing string type attributes when to make their size variable [with H5T_VARIABLE] or known size. Or how to distinguish these on the javascript side.

**Comment by rimmartin** [comment]
Have both fixed and variable attributes
