### ISSUE TITLE
Reorganizing into coordinated projects under HDF-NI

### ISSUE THREAD

**Issue by rimmartin** [HDF-NI/hdf5.node#17]
With different groups developing their own application it makes sense the core hdf5.node have only the native interface independently and reference and other layers separated into dependent projects.

This may help forks be pull compatible.

The reference editor/viewer in it's own project.

I'm experimenting with a web socket API layer based on ws and bson.

There could be a layer specializing in image api to browsers as well

Any ideas?

**Comment by vincent-tr** [comment]
I totally agree with this task.

Indeed, I think it is better to have separate low level binding, and high level editor/viewer, which may not be coupled with the low level api.

**Comment by rimmartin** [comment]
This is great!

I'l check the other platform builds, reduce the readme.md and publish it.
