### ISSUE TITLE
Reusing a typed array for writing a dataset causes a fatal error

### ISSUE THREAD

**Issue by Enet4** [HDF-NI/hdf5.node#23]
Considering this code snippet:

```
const hdf5 = require('hdf5').hdf5;
const h5lt = require('hdf5').h5lt;
const Access = require('hdf5/lib/globals').Access;
const H5Type = require('hdf5/lib/globals').H5Type;

var file = new hdf5.File('t.h5', Access.ACC_CREAT);
var data = new Float32Array(10);
data.type = H5Type.H5T_NATIVE_FLOAT;
data.rank = 3;
data.sections = 1;
// create dataset with data
h5lt.makeDataset(file.id, 'data', data);

data[3] = 5;

// reuse typed array to overwrite content
h5lt.writeDataset(file.id, 'data', data);

file.close();
```

This program fails with the following message (master branch, Node.js v5.8.0):

> FATAL ERROR: v8::ArrayBuffer::Externalize ArrayBuffer already externalized
> Aborted (core dumped)

**Comment by rimmartin** [comment]
This is fundamental to V8 native side at this time.  I'll relook at the state of this in the latest v8 version and see if better error handling is now possible

**Comment by rimmartin** [comment]
In nodejs v9.9.0 they have a way to get to content without the Externalize.  I've committed the change

**Comment by rimmartin** [comment]
Will be testing backward version compatibility

**Comment by rimmartin** [comment]
works from nodejs v8.0.0. onward
