### ISSUE TITLE
`npm test` and `mocha test` fail

### ISSUE THREAD

**Issue by shumway** [HDF-NI/hdf5.node#24]
### Problem

```
$ mocha test
module.js:328
    throw err;
    ^

Error: Cannot find module './build/Release/hdf5'
```
### Issues
- I am probably doing something wrong, but I can't find documentation.
- I know `hdf5` is installed correctly because I can use it directly from the node REPL.
- If I only `sudo npm install -g` then `npm test` gives an error about misiing co-mocha, which is in the package.json devDependencies. Doing `npm install` local doesn't work, but it does install the co-mocha dependency.
- The testing strategy and test status are not documented anywhere that I could find. I'd like to add that to the documentation pages and refer to it on the getting started / install landing page.
- Do we want to add continuous integration on https://travis-ci.org and a test status badge on the readme.md?

I can work on this, but some feedback from current developers on the state of the test suite would be helpful. Any suggestions or requests regarding testing are welcome.

**Comment by vincent-tr** [comment]
Hi,

Can you try :
`
./node_modules/.bin/mocha test
`
I think we may change the package.json test section to use locally installed mocha version, installed as devDependency as above.

When you execute `npm install` does it execute (and build) without errors ?

**Comment by vincent-tr** [comment]
Concerning automated integration tests, I don't know what to think.
I was using already existing tests, just added the one for the changed I made.
If the project is growing up, it can be a good idea.

**Comment by shumway** [comment]
Thanks! It looks like the problem I had was that I was using node from MacPorts. The permissions appear to be set up funny, so that `npm install` wasn't working and I had to use `sudo npm install -g`.

I downloaded node v4.4.1 LTS for mac, which installed node in /usr/local/node, then I ran:

```
npm install --hdf5_home_mac=/opt/local
```

to build with the MacPorts HDF5 installed in my /opt/local directory. That worked well, though it took me several minutes to figure out the --hdf5_home_mac flag (--hdf5_home_linux didn't work). Perhaps --hdf5_home would be simpler—I don't know what we gain by including the OS in the flag.

Once that was installed, running `npm test` worked well. I see 64 test passing, 5 pending, and one HDF5-DIAG error:

```
$ npm test
...
  testing c++ interface 
    create an h5 and group 
      ✓ should be >0 
      ✓ reopen of pmc should be >0
      ✓ should be >0 
      ✓ initial should be >0 
      ✓ move should be 1 
      ✓ move should be pmcservices 
      ✓ should have one child of type group 
HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 0:
  #000: H5T.c line 2146 in H5Tset_size(): size must be positive
    major: Invalid arguments to routine
    minor: Bad value
      ✓ should add an attribute to the file 


  64 passing (328ms)
  5 pending
````

**Comment by shumway** [comment]
The advantages I've seen for continuous integration on travis-ci:

- It's a backup check on the test status with multiple developers (not crucial right now)
- It documents the build instructions for a new system. I've found this very useful for C++ packages with dependencies on linux distros, but it's not as crucial with npm modules. The HDF5 dependency and different build instructions for mac, windows, and linux may make this worthwhile for hdf5.node.
- It may be useful to check for regressions if we support several node versions.
- It can be useful for generating distributable binaries. Not sure how this complements or duplicates AWS.
- New users may like the peace of mind seeing “build:passing” at the top of the README, with a link to the latest travis-ci build / test log. I find it's a nice sanity check if I'm having trouble installing a package on my machine.

No urgency, just offering to add travis-ci support if/when we want it.

**Comment by vincent-tr** [comment]
Indeed that could be a great advantage :)

**Comment by rimmartin** [comment]
Is this https://travis-ci.org/?

I'm looking into it; and how it works with native code or if it could be made to work with prebuilts

**Comment by rimmartin** [comment]
well built and ran the unit tests on https://travis-ci.org/ 
https://travis-ci.org/HDF-NI/hdf5.node

It was a ubuntu build.  From their docs it may be possible to build on mac as well.

**Comment by rimmartin** [comment]
mac is testing on travis-ci as well
