### ISSUE TITLE
1.10.0 series hdf5

### ISSUE THREAD

**Issue by rimmartin** [HDF-NI/hdf5.node#25]
Working on support for the new features which I've wanted for my projects for a very long time. https://www.hdfgroup.org/HDF5/docNewFeatures/index.html These are great features!  Will keep this interface compatible with 1.8.x.

**Comment by rimmartin** [comment]
hid_t is 8 byte and can;t be represented in javascript with the double which limits integers to 53 bit
javascript 64 bit integer aren't available.

Looking to handle these for file, group and dataset id's  Since we don't do arithmetic on these could possibly make them strings or a custom javascript object

**Comment by rimmartin** [comment]
Went with a NodeHDF5:Int64 wrapper for long long.  Feeding this through the code worked without requiring code changes on the javascript side.  Stays at 64 bit.  Javascript may implement a replacement and at that time will swap this out.

Tests are running with hdf5 1.10.x and 1.8.x

**Comment by rimmartin** [comment]
Haven't added any unique to 1.10 features yet some might be available by nature; writing from some instance and reading from another instance.  Have to come up with tests

**Comment by rimmartin** [comment]
Hi @Y--   I remember the hdf5_serial.so issue; my build of hdf5-1.10.0-patch1 doesn't make those.  Trying to recall; are these from system installs of hdf5?

Would a sym link solution work for your application?  For example

```
cd /usr/lib/x86_64-linux-gnu
sudo ln -s libhdf5_serial.so.8.0.2 libhdf5.so
sudo ln -s libhdf5_serial_hl.so.8.0.2 libhdf5_hl.so
```

This would allow for many more users

**Comment by Y--** [comment]
@rimmartin I'm not sure what is the `hdf5_serial` issue?
On Mac there is no such lib or did I miss something?

**Comment by rimmartin** [comment]
Referring to the binding.gyp; it was linking -hdf5-serial.so directly

**Comment by rimmartin** [comment]
some docker image has the 1.10 as libhdf5_serial.so?

**Comment by Y--** [comment]
Well I actually had to revert this change: https://github.com/sutoiku/hdf5.node/commit/3e7c6b7ad609c95442b98b30a4741dff5b85ff54 because that is an issue for us: on Debian distributions, when you `apt-get install libhdf5-serial-dev` you get the following libraries:

```
/usr/lib/x86_64-linux-gnu/libhdf5_serial.so
/usr/lib/x86_64-linux-gnu/libhdf5_serialhl_fortran.so
/usr/lib/x86_64-linux-gnu/libhdf5_serial_fortran.so
/usr/lib/x86_64-linux-gnu/libhdf5_serial_hl.so
/usr/lib/x86_64-linux-gnu/libhdf5_hl_cpp.so
/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so
/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_hl_cpp.so
/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5hl_fortran.so
/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_fortran.so
/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_cpp.so
/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_hl.so
/usr/lib/x86_64-linux-gnu/libhdf5_cpp.so
```

So the viable solutions that I can see are:
* using `libhdf5_serial.so`
* using `hdf5/serial/libhdf5.so`
* creating symlinks (as you suggested)

I would be open to any solution, even if I have a preference for one which doesn't involve creating symlinks :-)
I'm not sure I actually understand why it would "allow for many more users" as you said?
One way or the other some users will have to tweak something. Or am-I missing something?

**Comment by rimmartin** [comment]
People are still using 1.8.X and I'm not sure what build feature makes the libhdf5_serial.so. 

I've been trying to get build of 1.10.0-patch1 to produce the serial.

/usr/lib/x86_64-linux-gnu/libhdf5_serial.so== /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so ?

**Comment by rimmartin** [comment]
```
npm install --hdf5_home_linux=/usr/lib/x86_64-linux-gnu/hdf5/serial
```
?  But the includes aren't under this as home either

```
npm install --hdf5_serial=true
```
?

**Comment by Y--** [comment]
Unfortunately I'm not familiar enough with the libraries in their build so I can't say for sure those two libraries are equivalent, but right now our tests are green with both :-)

Even if that isn't ideal, we could add the `--hdf5_` flag to our build I guess.

**Comment by rimmartin** [comment]
Maybe we sleep on it and think tomorrow
