### ISSUE TITLE
"The specified module could not be found" Windows 10 - x64

### ISSUE THREAD

**Issue by fmanso** [HDF-NI/hdf5.node#27]
Hello,

First, thanks for your work. 

After compiling successfully I tried just this line of code:

> var hdf5 = require('hdf5').hdf5;

And I get the following error

> module.js:568
>   return process.dlopen(module, path._makeLong(filename));
>                  ^
> 
> Error: The specified module could not be found.
> \\?\D:\Users\Broker\Proyectos\tfg\hdf5\node_modules\hdf5\build\Release\hdf5.node
>     at Error (native)
>     at Object.Module._extensions..node (module.js:568:18)
>     at Module.load (module.js:458:32)
>     at tryModuleLoad (module.js:417:12)
>     at Function.Module._load (module.js:409:3)
>     at Module.require (module.js:468:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (D:\Users\Broker\Proyectos\tfg\hdf5\node_modules\hdf5\index.js:4:25)
>     at Module._compile (module.js:541:32)
>     at Object.Module._extensions..js (module.js:550:10)

I double check that the file hdf5.node exists on that path. 

May you help me, please?

**Comment by vincent-tr** [comment]
Can you try please:
`cd D:\Users\Broker\Proyectos\tfg\hdf5\node_modules\hdf5\`
`./node_modules/.bin/node-pre-gyp rebuild`

I'm surprised that you have this directory structure as part of your path: `hdf5\node_modules\hdf5`
Did you create a repo named 'hdf5', which requires hdf5.node ?

**Comment by fmanso** [comment]
It is just a directory for testing hdf5.node. It has only one file app.js with the require.

**Comment by fmanso** [comment]
I guess you search this:

> d:\Users\Broker\Proyectos\tfg\hdf5\node_modules\hdf5>node_modules\.bin\node-pre-gyp rebuild
> node-pre-gyp info it worked if it ends with ok
> node-pre-gyp info using node-pre-gyp@0.6.11
> node-pre-gyp info using node@6.2.0 | win32 | x64
> [hdf5] Removing "d:\Users\Broker\Proyectos\tfg\hdf5\node_modules\hdf5\lib\binding"
> node-pre-gyp ERR! build error
> node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd clean' (Error: spawn node-gyp.cmd ENOENT)
> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\Users\Broker\Proyectos\tfg\hdf5\node_modules\hdf5\node_modules\node-pre-gyp\lib\util\compile.js:77:29)
> node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:188:7)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:202:12)
> node-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:348:16)
> node-pre-gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
> node-pre-gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:98:9)
> node-pre-gyp ERR! System Windows_NT 10.0.10586
> node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "d:\\Users\\Broker\\Proyectos\\tfg\\hdf5\\node_modules\\hdf5\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "rebuild"
> node-pre-gyp ERR! cwd d:\Users\Broker\Proyectos\tfg\hdf5\node_modules\hdf5
> node-pre-gyp ERR! node -v v6.2.0
> node-pre-gyp ERR! node-pre-gyp -v v0.6.11
> node-pre-gyp ERR! not ok
> Failed to execute 'node-gyp.cmd clean' (Error: spawn node-gyp.cmd ENOENT)

**Comment by vincent-tr** [comment]
You should install node-gyp, as a global package: https://github.com/nodejs/node-gyp
It is used to compile native parts of modules, node-pre-gyp relies on it.

**Comment by fmanso** [comment]
Ops!. Thank you so much. It is now working.

**Comment by rimmartin** [comment]
I'll add about this in documentation; I get so use to node-gyp being there I forget
