### ISSUE TITLE
Reading string attribute from group returns weird results

### ISSUE THREAD

**Issue by fmanso** [HDF-NI/hdf5.node#28]
Hello,

I am trying to read an string attribute and I am having two problems. The first one is that using the same file the string returned is not the same every run. The second one is related to charset, I think.

I attached a sample. The HDF5 file only have one group with attributes. The problem is the string attribute called 'name'. The code is this:

> 
> var HDF5 = require('hdf5');
> var HDF5_GLOBALS = require('hdf5/lib/globals');
> var hdf5 = HDF5.hdf5;
> var h5lt = HDF5.h5lt;
> var Access = HDF5_GLOBALS.Access;
> 
> var hdf5File = new hdf5.File("sample.h5", Access.ACC_RDONLY);
> var hdf5Group = hdf5File.openGroup("neuron_layer_0");
> 
> hdf5Group.refresh();
> console.dir(hdf5Group);
> hdf5Group.refresh();
> console.dir(hdf5Group);
> hdf5Group.refresh();
> console.dir(hdf5Group);

And the result is:
![captura](https://cloud.githubusercontent.com/assets/673232/16111557/640b43b0-33b3-11e6-9bce-4f3431e19ec9.PNG)

HDFView show this properties on the group:
![image](https://cloud.githubusercontent.com/assets/673232/16111616/9fbf6576-33b3-11e6-8e4c-011c4d4c22cc.png)

[sample.zip](https://github.com/HDF-NI/hdf5.node/files/318028/sample.zip)

**Comment by rimmartin** [comment]
Thank you for the sample and presentation of problem.   Will study it

**Comment by rimmartin** [comment]
It is a variable length string attribute; I'm adding support for it.  Should get it over the weekend

**Comment by rimmartin** [comment]
Beginning to read. Have to think how to keep the difference of the string type in javascript to be able retain type when flushing back to the h5.

Also  i see you have array of doubles also as an attribute. I'll add more support for attributes in general including when they are arrays

**Comment by fmanso** [comment]
Great, thank you so much.

**Comment by rimmartin** [comment]
For where the type needs to be preserved I'm putting in string objects when writing and returning string objects with the type.

reading
```
var hdf5Group = hdf5File.openGroup("neuron_layer_0");
hdf5Group.refresh();
var type=hdf5Group.name.type;
console.dir(hdf5Group.name);
```
where type will be "variable-length" and name is "mflayer"

For writing
```
var hdf5Group = hdf5File.openGroup("neuron_layer_0");
var name=new String("mflayer");
name.type="variable-length";
hdf5Group.name=name;
```

Hopefully a few more evenings

**Comment by fmanso** [comment]
Looks nice, thanks !

**Comment by rimmartin** [comment]
There is now a test that creates an h5 with attributes similar to yours:
https://github.com/HDF-NI/hdf5.node/blob/master/test/test_attributes.js

```
mocha --harmony --require should --require co-mocha ./test/test_attributes.js #2> /dev/null
```

adding other changes and tests before publishing so you might want to clone from here.  Especially if you have other as yet unsupported h5's.

**Comment by fmanso** [comment]
Thanks. I will be able to try it on next monday, but I am not sure I am going to know how to build from cloned repo. Please tell me when it is available in npm. Thanks.

**Comment by fmanso** [comment]
I managed to compile and test. It is working like a charm. Thank you !

**Comment by rimmartin** [comment]
Oh great!  I'll publish after getting a few more types handled
