### ISSUE TITLE
Discovering groups and datasets in existing HDF5

### ISSUE THREAD

**Issue by duckontheweb** [HDF-NI/hdf5.node#35]
Is there a way to discover the group and dataset IDs within an existing file? I don't see anything in the documentation and inspecting an `hdf5.File` object doesn't show anything that might be useful in figuring out the id to be used in a call to `file.openGroup()`.

**Comment by zszszsz** [comment]
file.getMemberNames()
and
group.getMemberNames()

**Comment by rimmartin** [comment]
That is right.  I see I need to add it to the docs for file.
