### ISSUE TITLE
Error 1083: can not open include file: 'hdf5.h': No Such file or directory

### ISSUE THREAD

**Issue by MaQsoodShah** [HDF-NI/hdf5.node#37]
I am using windows 10 opencv 3.0.0 Vs 2013, when i debug the program it gives me the following errors:
Error 1083: can not open include file: 'hdf5.h': No Such file or directory
IntelliSense: can not open source file "hdf5.h"

even i link libraries etc by a good way. "hdf5.h" exist in C:\opencv-3.0.0\opencv\build\include\opencv2\flann but still it is giving me issue. can anybody help me?

Thanks

**Comment by rimmartin** [comment]
Your build line?
```
<your projects build command>   --fallback-to-build --hdf5_home_win=<your native hdf path>
```
where <your native hdf path> has the hdf5 include and lib folder for hdf5?

**Comment by MaQsoodShah** [comment]
sorry, i didn't understand what you mean. i only have hdf5.h file in C:\opencv-3.0.0\build\include\opencv2\flann\hdf5.h   except this hdf5 file, i dnt any hdf5 in my pc.

**Comment by MaQsoodShah** [comment]
i downloaded HDF and isntalled in C:\Program Files\HDF_Group\HDF5\1.8.18, now what to do next?
what do you mean by <your projects build command>   --fallback-to-build --hdf5_home_win=<your native hdf path>

**Comment by rimmartin** [comment]
--fallback-to-build has to do with prebuilts I put on Amazon; if your case matches up it just downloads them(no need to build in that case).

```
--hdf5_home_win=C:\Program Files\HDF_Group\HDF5\1.8.18
```
your install location is passed to your npm install and even if hdf5.node(hdf5) is a package within another project this switch will tell hdf5.node where the native hdf5 is located  when building.  See https://github.com/HDF-NI/hdf5.node/blob/master/binding.gyp#L4
It replaces this build variable from command line.

Make sure you have node-gyp installed; node-pre-gyp uses it

**Comment by rimmartin** [comment]
which nodejs version are you using?

**Comment by yylovess** [comment]
I have the same problem, I am using windows 10 , Vs 2013. When I compile a project. These errors happen:
Error 1083: can not open include file: 'hdf5.h': No Such file or directory
IntelliSense: can not open source file "hdf5.h".

But I am sure I have linked the project to the directory where there is the file “hdf5.h”. 
How do you solve this errors? Thank you. @rimmartin @MaQsoodShah

**Comment by rimmartin** [comment]
what is your build command?

```
npm install --hdf5_home_win=C:\Program Files\HDF_Group\HDF5\1.8.18
```
--hdf5_home_win needs to point to base directory of hdf5 native installation

**Comment by yylovess** [comment]
Thank you very much for your reply. I have solved this problem.
What I did is change the platform to x64. @rimmartin
