### ISSUE TITLE
getting dataset's datatype

### ISSUE THREAD

**Issue by rimmartin** [HDF-NI/hdf5.node#40]
Hi @Y-- 

Do we have redundant methods in getting this info? the fIle or groups have a method called getDataType(name) that takes the name of a child and returns the type mapped to H5Type's http://hdf-ni.github.io/hdf5.node/ref/globals.html#h5type for the javascript side.

http://hdf-ni.github.io/hdf5.node/ref/groups.html 

and h5lt.readDatasetDatatype(id, name) where id is file or group id. that returns a raw type.  Is the raw form working and what is being utilities? Or is it actually an address?  The native side types aren't real enumerations if I'm remembering right

What do you think?

**Comment by rimmartin** [comment]
And @Y--  wow does that build fast!  Got my first build of it.  I built with 1.8.17 and all 73 tests passed!

Almost don't feel the build

**Comment by rimmartin** [comment]
hdf5-1.10.0-patch1 works!  Nice!

**Comment by Y--** [comment]
I'm a bit confused with the API regarding that is supposed to provide the dataset type indeed.
@gpichot do you remember why we have these two?

**Comment by rimmartin** [comment]
If you are not using the one h5lt.readDatasetDatatype(id, name) I'll get rid of it

**Comment by Y--** [comment]
No we're not using this method and if we need to get the type we should definitely use the `getDataType` one. Sorry for the confusion.

**Comment by rimmartin** [comment]
Oh the confusion comes from time duration on me head till I look at things again:-)
