### ISSUE TITLE
npm build error on h5_lt.hpp

### ISSUE THREAD

**Issue by hyoklee** [HDF-NI/hdf5.node#46]
> ../src/h5_lt.hpp:35:17: error: unused variable 'maxsize' [-Werror,-Wunused-variable]

If I remove the following line, compilation works on Mac.

`const hsize_t maxsize = H5S_UNLIMITED;`

**Comment by rimmartin** [comment]
-Werror is set on the mac build whih makes warnings become errors; this could be less strict.

But this particular unused variable would be used in 
https://github.com/HDF-NI/hdf5.node/blob/master/src/h5_lt.hpp#L36
as 
https://github.com/HDF-NI/hdf5.node/blob/master/src/h5_lt.hpp#L1329
yet it was causing a crash in the underlying hdf5 library.  Commenting out is the way to go for now; I'll do it to the repository tonight

**Comment by rimmartin** [comment]
commented out in master
