### ISSUE TITLE
Default libhdf5 path on Ubuntu and similar distros

### ISSUE THREAD

**Issue by mizzao** [HDF-NI/hdf5.node#50]
On Ubuntu after installing `libhdf5-dev`, I need to use the following command to install this package:

```
npm i hdf5 --hdf5_home_linux=/usr/lib/x86_64-linux-gnu/hdf5/serial
```

Would it be possible to add `/usr/lib/x86_64-linux-gnu/hdf5/serial` to the list of paths to search? This would make it easier for someone else to run `npm install` without having to dig this up.

**Comment by rimmartin** [comment]
Hi,

This list of paths is a binding.gyp thing?  I'll learn about it some more

**Comment by rimmartin** [comment]
@vincent-tr ? Would this adversely effect your build?

**Comment by NINI1988** [comment]
Hi,

I would also like, when the install command `sudo apt install libhdf5-dev` would be included in the documentation for installing this module in ubuntu. It took me some time to get the correct package.

**Comment by rimmartin** [comment]
Will document some more.  The ttravis-ci build uses the hdf5 dev install just fine
