### ISSUE TITLE
Reading attributes from datasets returns weird results

### ISSUE THREAD

**Issue by bsrdjan** [HDF-NI/hdf5.node#52]
The same issue like for groups attributes (https://github.com/HDF-NI/hdf5.node/issues/28), I am facing for dataset attributes, get values which look corrupted. I can provide the sample and more info if needed?

**Comment by rimmartin** [comment]
Yea anything that gives me an idea of what is going on would help; I will work on this project on the weekend(work days are loaded)

**Comment by rimmartin** [comment]
It's an array of variable sized strings?

**Comment by bsrdjan** [comment]
Thank you so much @rimmartin for your work on this module and fast response.

Please find sample data attached and the output of reading attribute with `group.getDatasetAttributes`:

```shell
scada/active_power
{ initial_time: '�c@\u0003\u0001',
  time_step: '�`@\u0003\u0001',
  unit: '�w@\u0003\u0001' }

scada/generator_speed
{ initial_time: '��@\u0003\u0001',
  time_step: '',
  unit: 'P�@\u0003\u0001' }
```

[sample.zip](https://github.com/HDF-NI/hdf5.node/files/1668923/sample.zip)

**Comment by rimmartin** [comment]
Ok, we'll see over the weekend

**Comment by rimmartin** [comment]
It's reading from your sample.h5 now.  Thanks for it.  I haven't published to npm yet; you can use "hdf5": "HDF-NI/hdf5.node", in your project's package.json to pull it from github.  If you need it published I'll do it in the next couple of days.

**Comment by bsrdjan** [comment]
Thanks @rimmartin, experimental release is just fine.

Installation works on Linux and fails on OSX, probably because of the compiler flag required for "mac":
```shell
../src/h5_file.cc:201:22: error: extra tokens at end of #ifdef directive [-Werror,-Wextra-tokens]
#ifdef  H5_VERSION_GE(1,10,0)
                     ^
                     //
1 error generated.
```

**Comment by rimmartin** [comment]
Ah that is something new I was adding for Single-Write-Multi-Read enabling for 1.10.x versions; I'll test on a mac tonight was well if it skips that code for 1.8.x version of node

**Comment by rimmartin** [comment]
I commented the #ifdef  H5_VERSION_GE(1,10,0) segement temporarily so it should build on darwin

**Comment by bsrdjan** [comment]
Thank you @rimmartin . I tested and get following output on Mac now:

```shell
  CXX(target) Release/obj.target/hdf5/src/h5_group.o
  SOLINK_MODULE(target) Release/h5im.node
  SOLINK_MODULE(target) Release/h5pt.node
  SOLINK_MODULE(target) Release/h5ds.node
../src/methods.cc:581:40: error: unused variable 'idx' [-Werror,-Wunused-variable]
      hsize_t                          idx = args[0]->Int32Value();
                                       ^
../src/methods.cc:583:36: error: unused variable 'argc' [-Werror,-Wunused-variable]
      const unsigned               argc = 2;
                                   ^
2 errors generated.
make: *** [Release/obj.target/hdf5/src/methods.o] Error 1
make: *** Waiting for unfinished jobs....
../src/h5_file.cc:201:11: error: unused variable 'file' [-Werror,-Wunused-variable]
    File* file = ObjectWrap::Unwrap<File>(args.This());
          ^
1 error generated.
```

**Comment by rimmartin** [comment]
ah warnings are set to error; let me comment that out or move it within the commneted segment...

**Comment by rimmartin** [comment]
pushed another try

**Comment by rimmartin** [comment]
oh there are more ok wait ...

**Comment by rimmartin** [comment]
ok got all three

**Comment by bsrdjan** [comment]
Thanks, it works for me now, both the installation and dataset attributes reading.
