### ISSUE TITLE
Cannot read top-level attributes of file

### ISSUE THREAD

**Issue by jprctr** [HDF-NI/hdf5.node#53]
I'm using hdf5.node to load and parse [hdf5 biom files](http://biom-format.org/documentation/format_versions/biom-2.1.html).

The biom format requires several top-level attributes on the file. Initially, when the file is loaded by hdf5.node, only the id is visible on the File object, but calling .getNumAttrs() on the file object does return the correct number (8). 

After calling refresh() on the file object, two more of the expected attributes, creation-date and format-url, both strings, become visible. However, this also causes a syntax error `unsupported data type`. 

I believe this is because at least one of the 5 remaining attributes on the file object is not being coerced into a data type supported by node, but if there is a simple solution I've missed, please let me know. The remaining data types are tuple, list of ints, int, and string.

[Sample Data](https://github.com/biocore/biom-format/blob/master/examples/rich_sparse_otu_table_hdf5.biom)

Sample Code:
```
const hdf5 = require('hdf5').hdf5;
const Access = require('hdf5/lib/globals').Access;

const file = new hdf5.File('rich_sparse_otu_table_hdf5.biom', Access.ACC_RDONLY);
console.log(file);
console.log(file.getNumAttrs());
file.refresh();

```

**Comment by rimmartin** [comment]
Thanks for the sample data.  I'll run thru and see what data types to add support for.

**Comment by rimmartin** [comment]
Ah, these are 64 bit.  Javascript has no primitive with this bit resolution.  The google v8 doesn't have anything for it.

For hdf5.node I made a custom holder for 64 bit id's called Int64.  We could use this to return these attribute data types as well.  It is possible to get the string representation with Int64.toString method which javascript will use in print statements.  Could also return Array's of Int64's as well.

To write back to h5.biom files any attribute within 32 bit can be written with new hdf5.Int64(0)
I will be adding instantiation to take a string representation of a 64 bit like new hdf5.Int64("0")

Would this solution work for you?

**Comment by rimmartin** [comment]
Could also add a hdf5.IUint64 for unsigned ones

**Comment by jprctr** [comment]
If the remaining attributes come wrapped in your hdf5.Int64 container in the same way the id attribute does that would be perfect. That solution would work well for me - thanks!

**Comment by rimmartin** [comment]
Ok, I'll move forward

**Comment by rimmartin** [comment]
The repository HEAD is read int64_t & uint64_t as single values or arrays as attributes.

Adding writing using a string representation

**Comment by rimmartin** [comment]
The writing of Uint64 and Int64 scalar and array attributes have been added

```
            file.nnz=new hdf5Lib.hdf5.Int64("15");
            file.unnz=new hdf5Lib.hdf5.Uint64("40");
            var fv=new Array(2);
            fv[0]=new hdf5Lib.hdf5.Int64("2");
            fv[1]=new hdf5Lib.hdf5.Int64("1");
            file["formart-version"]=fv;
            var ufv=new Array(2);
            ufv[0]=new hdf5Lib.hdf5.Uint64("20");
            ufv[1]=new hdf5Lib.hdf5.Uint64("10");
            file["uformart-version"]=ufv;
            file.flush();

```

**Comment by jprctr** [comment]
`file.refresh()` is working for me at [e857f0eef9c8c7019935b013611a4b0b9db1df82](https://github.com/HDF-NI/hdf5.node/commit/e857f0eef9c8c7019935b013611a4b0b9db1df82) - thanks!

When do these changes typically make their way onto the NPM registry?

**Comment by rimmartin** [comment]
Will do soon.  I now have access to a mac talking with github to test it is working on darwin with static hdf5 native libraries https://github.com/HDF-NI/hdf5.node/issues/56. Hopefully over the weekend and publish to npm on Monday

**Comment by rimmartin** [comment]
Postponed for a while but getting close now that I can build on a mac via travis-ci.org
https://travis-ci.org/HDF-NI/hdf5.node/
