### ISSUE TITLE
Read group attributes possible?

### ISSUE THREAD

**Issue by bsrdjan** [HDF-NI/hdf5.node#54]
Is it possible to read attributes attached to group, not the dataset? Which method to use?

**Comment by rimmartin** [comment]
If you refresh and the attributes should be on the group object
https://hdf-ni.github.io/hdf5.node/tut/attributes-tutorial.html

you should be able to treat them just like any other owned properties on a javascript object.

If this is still unclear, do you have an example of what you are trying to achieve?

**Comment by bsrdjan** [comment]
Many thanks, works perfect!

**Comment by rimmartin** [comment]
good!
