### ISSUE TITLE
Reading hyperslabs fails

### ISSUE THREAD

**Issue by joshua-gould** [HDF-NI/hdf5.node#55]
Example:
**Prerequisites: Download hdf5 file from http://pklab.med.harvard.edu/velocyto/hgForebrainGlut/hgForebrainGlut.loom**

```
var hdf5 = require('hdf5').hdf5;
var h5lt = require('hdf5').h5lt;
var Access = require('hdf5/lib/globals').Access;
var file = new hdf5.File('hgForebrainGlut.loom', Access.ACC_RDONLY);
var dim = file.getDatasetDimensions('matrix');
for (var i = 0; i < dim[0]; i++) {
  var buffer = h5lt.readDatasetAsBuffer(file.id, 'matrix', {
    start: [i, 0],
    stride: [1, 1],
    count: [1, dim[1]]
  });
}
```

Error:
HDF5-DIAG: Error detected in HDF5 (1.8.20) thread 0:
  #000: H5S.c line 1382 in H5Screate_simple(): maxdims is smaller than dims
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.8.20) thread 0:
  #000: H5Dio.c line 147 in H5Dread(): not a data space
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.8.20) thread 0:
  #000: H5S.c line 390 in H5Sclose(): not a dataspace
    major: Invalid arguments to routine
    minor: Inappropriate type
SyntaxError: failed to read dataset

**Comment by joshua-gould** [comment]
Thanks.

**Comment by rimmartin** [comment]
This is a compressed dataset.  I've been working on getting compression capability.

I haven't tried a compressed dataset with hyperslabbing yet.  Studying this some more...

**Comment by rimmartin** [comment]
hdf5 forum tells me this is doable.
https://forum.hdfgroup.org/t/are-hyperslabs-and-compression-compatible/860

Looking for a c example. it may have to do with access property list for the reading step.  Looking...

**Comment by joshua-gould** [comment]
Awesome! Thanks so much.

**Comment by joshua-gould** [comment]
Any updates on how to fix this issue? Thanks.

**Comment by rimmartin** [comment]
I'm getting back to things.  Had a software release at work that consumed a lot of time

I'll make a small c/c++ app to test this out a bit; it really should be no different

**Comment by rimmartin** [comment]
in  some versions of hdf5 H5S_UNLIMITED didn't work.  You're making my recaller kick in:-)

**Comment by rimmartin** [comment]
I think that was it! Must reveal itself when it is a compressed h5. Survey for more places an array should be used

**Comment by rimmartin** [comment]
All other H5Screate_simple's have the maximum_dims NULL. Will need to see if any should be filed in to allow H5S_UNLIMITED

**Comment by rimmartin** [comment]
@joshua-gould  I committed changes after applying @NINI1988 's fix to this one as well.

**Comment by joshua-gould** [comment]
It works now! Thanks.
