### ISSUE TITLE
[Quick Question] Using stride with 1d array

### ISSUE THREAD

**Issue by OmarElGabry** [HDF-NI/hdf5.node#57]
Hello!

My question is, given this 1d array = `[1,2,3,4,5,6,7,8,9,10, ...]`, I need to select `[1,3,5,7,9, ...]`. So, I need to start from first element (index=0), and having a stride equals to 2 (select every other element). 

```
var hdf5 = require('hdf5').hdf5;
var h5lt = require('hdf5').h5lt;

var Access = require('hdf5/lib/globals').Access;
var file = new hdf5.File('inchies_1.h5');

var dataset = h5lt.readDataset(file.id, "inchies", {start: [0], stride: [2]});
```

What I will get is all the whole array starting from index=0, and stride will be ignored. I struggled with this for a while. So, I hope there is a workaround.

Thanks,
Omar

**Comment by NINI1988** [comment]
Stride will only be used when count is specified.

**Comment by rimmartin** [comment]
Yes.  I'll add an exception to let the developer know

**Comment by rimmartin** [comment]
added a test case for missing count throwing an exception.

made start default to origin and stride to 1
