### ISSUE TITLE
Add possibility to specify chunkSize in multiple dimensions

### ISSUE THREAD

**Issue by NINI1988** [HDF-NI/hdf5.node#68]
Is there a way to specify the chunk size in multiple dimensions seperatly?

Something like `h5lt.makeDataset(group.id, 'ds', buffer, { chunkSize: [50, 1000]});`

**Comment by NINI1988** [comment]
Yes it's possible.
It's a good decision to make it scalar for old users and also provide new functionality with an array.

**Comment by rimmartin** [comment]
This should now bee there. I need to make a unit tests to be sure

**Comment by NINI1988** [comment]
Wow, you are really fast. Thank you and a good way to add always unit tests.

**Comment by rimmartin** [comment]
test 'should be make a dataset with arrayed chunk size' in test_h5lt.js tests this
```
            h5lt.makeDataset(group.id, 'Arrayed-chunked Index', buffer, {rank:2, rows: 5, columns:2, chunkSize: [3,2]});

```
