### ISSUE TITLE
Node version not specified

### ISSUE THREAD

**Issue by NINI1988** [HDF-NI/hdf5.node#69]
The badge in the readme file says, `node: not specified`

We could add the version in the package.json file:
```
"engines": {
  "node": ">= x.x.x"
},
```

**Comment by rimmartin** [comment]
k, I'll test back thru the versions some more; I've only tested  a few so far

**Comment by rimmartin** [comment]
farthest back is nodejs v8.0.0

**Comment by NINI1988** [comment]
Good to know.

Are you doing this tests locally? Or do you have a test server?
Are you running under Linux or how do you test so many different versions?

**Comment by rimmartin** [comment]
I'm on linux with my laptop At work I ave a windows a mac box. The mac box is so old can't test with current versions of nodejs any more. Supposed to get a new one maybe this year.

There was some talk of travis-ci https://github.com/HDF-NI/hdf5.node/issues/24. 'll revisit this although I doubt t can help with mac's

**Comment by rimmartin** [comment]
Looking into a way to allow nodejs v7.x.x's to run as well

**Comment by rimmartin** [comment]
I've ripped out using the node-pre-gyp; probably dump the amazon 3 bucket for it unless travis-ci needs it; then might have t bring it back

**Comment by rimmartin** [comment]
nodejs v10.1.0 works albeit with a lot of deprecation warnings. Example

```
In file included from ../src/uint64.cc:1:0:
../src/uint64.hpp: In static member function ‘static void NodeHDF5::Uint64::New(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/uint64.hpp:55:159: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
         std::string value = args[args.Length() - 1]->IsUndefined() ? std::string("0") : std::string(*v8::String::Utf8Value(args[args.Length() - 1]->ToString()));
                                                                                                                                                               ^
In file included from /home/roger/.node-gyp/10.1.0/include/node/v8.h:26:0,
                 from ../src/uint64.hpp:4,
                 from ../src/uint64.cc:1:
/home/roger/.node-gyp/10.1.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^~~~~~~~~
/home/roger/.node-gyp/10.1.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~

Will check these out and see if still runs with v8.0.0
```

**Comment by rimmartin** [comment]
70 passing (420ms)
  8 pending

**Comment by rimmartin** [comment]
On node: not specified
I added the engines segment to package.json; this might only pick up after publishing

**Comment by rimmartin** [comment]
on win64 box:
```
  69 passing (1s)
  8 pending
  1 failing

  1) testing images
       read image and transfer
         should be 1.10.0 :

      AssertionError: expected '1.8.15' to be '1.10.1'
      + expected - actual

      -1.8.15
      +1.10.1
```
which is a good failure since I'm testing with 1.8.15

**Comment by rimmartin** [comment]
building on travis-ci now.  Can test and get mac build going from there I think

**Comment by rimmartin** [comment]
@NINI1988 nice cleanup on the readme!

**Comment by rimmartin** [comment]
I want to publish soon; I think this will show up from the npm repository
