### ISSUE TITLE
Can't catch broken hdf5 file

### ISSUE THREAD

**Issue by NINI1988** [HDF-NI/hdf5.node#73]
It is not possible to catch opening a broken hdf5 file.

```
try{
  var file = new hdf5.File('broken.h5', Access.ACC_RDONLY);
  file.close();
}catch(error){
  console.error(error);
}
```

[broken.zip](https://github.com/HDF-NI/hdf5.node/files/2034420/broken.zip)

Would it be possible to use the c++ version of hdf5 to catch exceptions?

**Comment by rimmartin** [comment]
This I believe is a different issue related to where 
```
v8::Isolate::GetCurrent()->ThrowException(
+            v8::Exception::TypeError(String::NewFromUtf8(v8::Isolate::GetCurrent(), ss.str().c_str())));
```
is valid to do.  c++ calls the same H5Fopen we do

I'm working on these

**Comment by rimmartin** [comment]
I use
```
throw  std::invalid_argument(ss.str());
```
to throw it over where Isolate GetCurrent works. the error = true needs to be set first

**Comment by rimmartin** [comment]
Is it ok if broken.h5 is committed to test/examples?

**Comment by rimmartin** [comment]
I've committed. Skipped the test until a broke.h5 example is available.

The exception is catching on the javascript side.

The H5Fopen is noisy on the cerr stream.

Adding a File.isHdf5 which calls H5Fis_hdf5

**Comment by NINI1988** [comment]
Yes, you can use the h5 file.

**Comment by rimmartin** [comment]
turned this test on

the cerr piped to terminal by default in h5 is noisy on this one.  Thinking about it

**Comment by NINI1988** [comment]
We could disable error printing in hdf5.

https://support.hdfgroup.org/HDF5/doc/H5.user/Errors.html

**Comment by rimmartin** [comment]
I've wanted to rdirect to a nodejs stream; a couple of time a nodejs native side stream was being introduced but didn't make the cut into their releases

Probably make it optional to disable or redirect to a callback function

**Comment by rimmartin** [comment]
or add a module for
https://support.hdfgroup.org/HDF5/doc/RM/RM_H5E.html

**Comment by rimmartin** [comment]
I think a release of v0.3.4 and then added error handling changes in next version would be good
