### ISSUE TITLE
Write_dataset new options error

### ISSUE THREAD

**Issue by NINI1988** [HDF-NI/hdf5.node#76]
Using writeDataset with new options properties course error because type is not defined.
https://github.com/HDF-NI/hdf5.node/blob/master/src/h5_lt.hpp#L840

Should we use:
```
if (buffer->Has(String::NewFromUtf8(v8::Isolate::GetCurrent(), "type"))) {
  type_id = toTypeMap[(H5T)buffer->Get(
    String::NewFromUtf8(v8::Isolate::GetCurrent(), "type"))->Int32Value()];
} else {
  get_type(options, [&](hid_t _type_id){type_id=_type_id;});
}
```
Or read the type from the datset itself:
```
hid_t H5Dget_type(hid_t dataset_id )
```

I would prefer the second way, because no one can forget to set the type.
Or could it be possible that someone writes different types to the same dataset?

**Comment by rimmartin** [comment]
Switched to second way. User shouldn't need to set the type at all for a write or read; only creation. Will commit soon

I think most are going into
https://github.com/HDF-NI/hdf5.node/blob/master/src/h5_lt.hpp#L821
because of the node::Buffer::HasInstance change

**Comment by rimmartin** [comment]
@NINI1988  check your case for this one?

**Comment by NINI1988** [comment]
I'll look on Monday.

**Comment by rimmartin** [comment]
Sure:-) Make better use of the weekend:-)

**Comment by NINI1988** [comment]
`write_dataset` with new options works. :+1:

**Comment by rimmartin** [comment]
At first nodejs had a buffer separate from the typed arrays; then v8 changes made them choose the Uint8Array as their buffer;  now in later versions(v8 on) the base class ArrayBufferView https://v8docs.nodesource.com/node-9.3/da/d3d/classv8_1_1_array_buffer_view.html of all typed arrays is considered  node::Buffer 

It was all nice and neat back then when the node::Buffer was separate and node::Buffer::HasInstance distinguished exactly.

To be compatible back to v8 it needs the difference of NODE_VERSION_AT_LEAST to know to check for IsUint8Array to use it differently if there is a type set in the type property (now in options) that isn't H5T_NATIVE_UINT8.

The extra calls to make_dataset_from_buffer, make_dataset_from_typed_array etc were introduced by Sutoiku although they weren't aware of the throws-are-scheduled nature of v8. But to organize the code a bit

**Comment by NINI1988** [comment]
Thanks for this explanation.
