### ISSUE TITLE
reat attributes written by python

### ISSUE THREAD

**Issue by aggem** [HDF-NI/hdf5.node#86]
Dear all,
I have a hdf5 file generated by a python script. The datasets contain 2 attributes "unit" (String, length = variable, Array size Scalar)  and "nuclides" (String, length = 7, Array size 51 according to hdf5view). 
When I'm reading the dataset using hdf5.node, I only see the "unit" attribute containing a cryptc value :"P!�". The other attribute "nuclides" is undefined. How can I acces the attributes?
Best Regards
Gerhard

**Comment by rimmartin** [comment]
Hi,
https://hdf-ni.github.io/hdf5.node/tut/attributes-tutorial.html getDatasetAttributes should retrieve them.

version of nodejs?

Have an example h5 you can send to me?

**Comment by aggem** [comment]
thanks for the quick reply! I'm using node v10.1.0. getDatasetAttributes crashes with a segmentation fault. I would like to send you an example, but don't know how (sorry I'm a newbie) . Markdown doesn't allow for attaching hdf5 files.

**Comment by rimmartin** [comment]
oh forgot; from npm (v0.3.3) or this repository?  Many changes to include v10.1.0

Planning to release v0.3.4 soon

**Comment by rimmartin** [comment]
https://github.com/HDF-NI/hdf5.ws/blob/master/package.json#L16
will tell npm to pull from github repository instead of the npm v0.3.3 repository

**Comment by aggem** [comment]
Hi rimmartin,
in the attached there are several groups, try e.g. LEG_L_KBA_FLUX/y.
Best Regards
Gerhard

Von: rimmartin [mailto:notifications@github.com]
Gesendet: Montag 4 Juni 2018 12:08
An: HDF-NI/hdf5.node <hdf5.node@noreply.github.com>
Cc: MAYER Gerhard <g.mayer@csd.ch>; Author <author@noreply.github.com>
Betreff: Re: [HDF-NI/hdf5.node] reat attributes written by python (#86)


Hi,
https://hdf-ni.github.io/hdf5.node/tut/attributes-tutorial.html getDatasetAttributes should retrieve them.

version of nodejs?

Have an example h5 you can send to me?

**Comment by rimmartin** [comment]
I'll give it a try this evening

**Comment by aggem** [comment]
Many thanks!

Von: rimmartin [mailto:notifications@github.com]
Gesendet: Montag 4 Juni 2018 13:16
An: HDF-NI/hdf5.node <hdf5.node@noreply.github.com>
Cc: MAYER Gerhard <g.mayer@csd.ch>; Author <author@noreply.github.com>
Betreff: Re: [HDF-NI/hdf5.node] reat attributes written by python (#86)


I'll give it a try this evening

**Comment by aggem** [comment]
I tried it with the github repository, but it didn't help.

**Comment by rimmartin** [comment]
k studying it now

**Comment by rimmartin** [comment]
You might need to zip it up to attach

**Comment by rimmartin** [comment]
thank you, working with it

**Comment by rimmartin** [comment]
I'm seeing the problem.  This is a good test; at work things for a while and then I'll get this

**Comment by rimmartin** [comment]
I'm now getting 
```
unit: mol/a
```
for the other property nuclides it seems to be a string delimited by  '\n' .  Is that what you want?

**Comment by rimmartin** [comment]
or an Array of 7 strings?

**Comment by rimmartin** [comment]
Yep got it; i all depends on the number of elements in a dataspace; getting this to work; will make greater changes in next version

**Comment by rimmartin** [comment]
this repository should work now.  A release to npm is coming

**Comment by aggem** [comment]
Many thanks, getDatasetAttributes works now as expected!
The only thing I noticed is that datasets returned from h5lt.readDataset still do not have the correct attributes.

Von: rimmartin [mailto:notifications@github.com]
Gesendet: Mittwoch 6 Juni 2018 04:43
An: HDF-NI/hdf5.node <hdf5.node@noreply.github.com>
Cc: MAYER Gerhard <g.mayer@csd.ch>; Author <author@noreply.github.com>
Betreff: Re: [HDF-NI/hdf5.node] reat attributes written by python (#86)


this repository should work now. A release to npm is coming

**Comment by rimmartin** [comment]
h5lt.readDataset should bring them back as properties.  This may become optional because some users may not want this happening automatically.  I'm consolidating the attribute code getting rid of dependency on H5LT: HDF5 Lite
https://github.com/HDF-NI/hdf5.node/issues/90
