### ISSUE TITLE
make_dataset_from_typed_array dont handle maxRows etc.

### ISSUE THREAD

**Issue by NINI1988** [HDF-NI/hdf5.node#87]
Would it be better to handle TypedArrays and Buffer in the same function?
The only difference is that TypedArrays dont need a type.

Also `make_dataset_from_buffer` function has many code lines. Maybe it would be better to split these into multiple functions?

**Comment by rimmartin** [comment]
depends on nodejs version

v6 to v8 -- Buffer is a UintArray
https://github.com/HDF-NI/hdf5.node/issues/20

v8 on Buffer is a ArrayBufferView, the base class of all the types

Then the options property type if it is 'exotic' as in not H5T_NATIVE_UINT8 thru H5T_NATIVE_DOUBLE then it is a buffer

We can feed thru the maxRows stuff here; type array stuff was added for when node::Buffer::HasInstance  changed it's behavior.

But we definitely can reorganize keeping the versions working from v6 to the v8.0.0 onward changes to node js

**Comment by rimmartin** [comment]
Although can we get to a release and then reorganize? then we'll take out the property way for rank, type, rows, columns etc and go with just the options way?

**Comment by rimmartin** [comment]
might work better to check if type(if set) is any of the H5T_NATIVE_XXXX types or not to distinguish from nodejs v8 onward

**Comment by NINI1988** [comment]
A release would make sense, because many errors are fixed in the last time.
I would also prefer `to check if type(if set)`.

Is it possible to run travis on multiple nodejs versions? So we could test nodejs 6, 8, 9, 10 for example.

**Comment by rimmartin** [comment]
I tried, it (nodejs) failed miserably on older versions; I can try 9 and 10

Also different compiler versions can be tried

A whole matrix of builds can be tried

I also would like to use a native hdf5 install on mac although the compiled ones seem to work better than libhdf5-dev ones even on linux

haven't tried win since the bash i would suspect be cmd instead.  Have to read docs on it if it is possible

**Comment by rimmartin** [comment]
Yep thanks to you many errors fixed.

**Comment by rimmartin** [comment]
hmm when I change yml to include another version

```
node_js:
  - "8"
  - "10"
```
it goes haywire on travis.  Their docs show between versions such as

```
node_js:
  - "iojs"
  - "7"
```
maybe the matrix needs something

The error is that it can't find g++7

```

**Comment by rimmartin** [comment]
Oh, notice on making a Buffer on the native side there are no constructors making it as the derived XXXXXArray (typed arrays); that's why all the distinction there too

**Comment by rimmartin** [comment]
ref
https://github.com/nodejs/node/issues/3419

**Comment by rimmartin** [comment]
https://docs.travis-ci.com/user/multi-os/
only mentions linux and osx

**Comment by rimmartin** [comment]
Well there goes the neighborhood; see banner up top M$
